[tool.poetry]
name = "discordbb"
version = "1.2.5beta"
description = ""
authors = ["Martin Røvang <martinrovang@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
discord = "^2.3.2"
beartype = "^0.19.0"
toml = "^0.10.2"
loguru = "^0.7.2"
pygithub = "^2.4.0"
flask = {extras = ["async"], version = "^3.0.3"}
uvicorn = "^0.32.0"


[tool.poetry.group.dev.dependencies]
nox = "^2024.4.15"
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
