[tool.poetry]
name = "discordbb"
version = "1.0.3"
description = ""
authors = ["Martin Røvang <martinrovang@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
discord = "^2.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
